apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-crud-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: golang-crud
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
