apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: golang-crud-production

resources:
  - ../../

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: golang-crud
    newTag: v1.0.0
